CREATE SCHEMA IF NOT EXISTS "account";

CREATE SCHEMA IF NOT EXISTS "course";

CREATE SCHEMA IF NOT EXISTS "professor";

CREATE TABLE IF NOT EXISTS "account"."session" (
    "token" "text",
    "user_agent" "text",
    "created_at" timestamp without time zone,
    "ip_address" "inet" NOT NULL,
    "id" bigint NOT NULL,
    "user_id" bigint
);

CREATE TABLE IF NOT EXISTS "course"."access_token" (
    "client_address" "inet" NOT NULL,
    "query_params" "text" NOT NULL,
    "expires_on" timestamp with time zone NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

CREATE TABLE IF NOT EXISTS "course"."course" (
    "tag" "text" NOT NULL,
    "name" "text" NOT NULL,
    "views" integer DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS "course"."file" (
    "id" bigint NOT NULL,
    "blob_name" "text" NOT NULL,
    "name" "text" NOT NULL,
    "type" "text" NOT NULL,
    "size" integer NOT NULL,
    "visible" boolean DEFAULT false NOT NULL,
    "reviewed" boolean DEFAULT false NOT NULL,
    "vt_report" json,
    "course_tag" "text" NOT NULL,
    "download_count" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "course"."file" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "course"."file_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "professor"."professor" (
    "email" "text" NOT NULL,
    "name" "text" NOT NULL,
    "college" "text" NOT NULL,
    "views" integer DEFAULT 0 NOT NULL,
    "visible" boolean DEFAULT true NOT NULL,
    "university" "text" NOT NULL,
    "aliases" "text"[]
);

CREATE TABLE IF NOT EXISTS "professor"."professor_course_history" (
    "email" "text" NOT NULL,
    "course_tag" "text" NOT NULL
);

CREATE TABLE IF NOT EXISTS "professor"."reply_like" (
    "session_id" bigint NOT NULL,
    "user_id" bigint,
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "reply_id" bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS "professor"."reply_name" (
    "name" character varying NOT NULL,
    "review_id" bigint NOT NULL,
    "session_id" bigint NOT NULL,
    "user_id" bigint
);

CREATE TABLE IF NOT EXISTS "professor"."review" (
    "id" bigint NOT NULL,
    "score" smallint NOT NULL,
    "positive" boolean NOT NULL,
    "content" "text" DEFAULT ''::"text" NOT NULL,
    "attachment" bigint,
    "professor_email" character varying NOT NULL,
    "ip_address" "inet",
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "visible" boolean DEFAULT true NOT NULL,
    "reviewed" boolean DEFAULT false NOT NULL,
    "session_id" bigint,
    "user_id" bigint,
    "uaeu_origin" boolean DEFAULT false NOT NULL,
    "like_count" integer DEFAULT 0 NOT NULL,
    "dislike_count" integer DEFAULT 0 NOT NULL,
    "language" "text" DEFAULT 'en'::"text" NOT NULL,
    "deleted_at" timestamp without time zone,
    "sort_index" bigint DEFAULT '-1'::integer NOT NULL,
    "gif" "text",
    "reply_count" bigint DEFAULT '0'::bigint NOT NULL,
    "course_taken" "text",
    "grade_received" "text",
    "student_verified" boolean DEFAULT false NOT NULL
);

CREATE TABLE IF NOT EXISTS "professor"."review_attachment" (
    "id" bigint NOT NULL,
    "mime_type" character varying NOT NULL,
    "size" integer NOT NULL,
    "width" integer NOT NULL,
    "height" integer NOT NULL,
    "visible" boolean,
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "blob_name" "text" NOT NULL,
    "ip_address" "inet"
);

CREATE TABLE IF NOT EXISTS "professor"."review_flag" (
    "review_id" bigint NOT NULL,
    "attribute" "text" NOT NULL,
    "score" double precision NOT NULL,
    "engine" "text" NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL
);

CREATE TABLE IF NOT EXISTS "professor"."review_rating" (
    "value" boolean NOT NULL,
    "ip_address" "inet" NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "review_id" bigint NOT NULL,
    "session_id" bigint NOT NULL,
    "user_id" bigint
);

CREATE TABLE IF NOT EXISTS "professor"."review_reply" (
    "id" bigint NOT NULL,
    "content" character varying DEFAULT ''::character varying NOT NULL,
    "gif" character varying,
    "visible" boolean DEFAULT true NOT NULL,
    "session_id" bigint NOT NULL,
    "user_id" bigint,
    "review_id" bigint NOT NULL,
    "mention_id" bigint,
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "op" boolean NOT NULL,
    "like_count" smallint DEFAULT '0'::smallint NOT NULL,
    "deleted_at" timestamp without time zone
);

CREATE TABLE IF NOT EXISTS "professor"."review_report" (
    "id" bigint NOT NULL,
    "review_id" bigint NOT NULL,
    "reason" "text" NOT NULL,
    "session_id" bigint NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "resolved" boolean DEFAULT false NOT NULL
);

CREATE TABLE IF NOT EXISTS "professor"."review_translation" (
    "review_id" bigint NOT NULL,
    "translated_text" "text" NOT NULL,
    "target" "text" NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."feedback_entry" (
    "feedback_id" bigint NOT NULL,
    "question" "text" NOT NULL,
    "answer" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."feedback_entry" ALTER COLUMN "feedback_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."feed_entry_feedback_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."feedback" (
    "id" bigint NOT NULL,
    "session_id" bigint NOT NULL,
    "completed" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "current_question" "text" NOT NULL
);

ALTER TABLE "public"."feedback" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."feedback_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "account"."session"
    ADD CONSTRAINT "session_pk" PRIMARY KEY ("id");

ALTER TABLE ONLY "course"."access_token"
    ADD CONSTRAINT "access_token_pkey" PRIMARY KEY ("client_address", "query_params");

ALTER TABLE ONLY "course"."course"
    ADD CONSTRAINT "course_pkey" PRIMARY KEY ("tag");

ALTER TABLE ONLY "course"."file"
    ADD CONSTRAINT "file_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "professor"."professor_course_history"
    ADD CONSTRAINT "professor_course_history_pkey" PRIMARY KEY ("email", "course_tag");

ALTER TABLE ONLY "professor"."professor"
    ADD CONSTRAINT "professor_pkey" PRIMARY KEY ("email");

ALTER TABLE ONLY "professor"."reply_like"
    ADD CONSTRAINT "reply_like_pkey" PRIMARY KEY ("session_id", "reply_id");

ALTER TABLE ONLY "professor"."reply_name"
    ADD CONSTRAINT "reply_name_pk_2" UNIQUE ("review_id", "name");

ALTER TABLE ONLY "professor"."reply_name"
    ADD CONSTRAINT "reply_name_pkey" PRIMARY KEY ("review_id", "session_id");

ALTER TABLE ONLY "professor"."review_attachment"
    ADD CONSTRAINT "review_attachment_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "professor"."review_flag"
    ADD CONSTRAINT "review_flag_pk" PRIMARY KEY ("review_id");

ALTER TABLE ONLY "professor"."review"
    ADD CONSTRAINT "review_pk" PRIMARY KEY ("id");

ALTER TABLE ONLY "professor"."review_rating"
    ADD CONSTRAINT "review_rating_pkey" PRIMARY KEY ("review_id", "session_id");

ALTER TABLE ONLY "professor"."review_reply"
    ADD CONSTRAINT "review_reply_pk" PRIMARY KEY ("id");

ALTER TABLE ONLY "professor"."review_report"
    ADD CONSTRAINT "review_report_pk" PRIMARY KEY ("id");

ALTER TABLE ONLY "professor"."review_translation"
    ADD CONSTRAINT "review_translation_pk" PRIMARY KEY ("review_id");

ALTER TABLE ONLY "public"."feedback_entry"
    ADD CONSTRAINT "feed_entry_pkey" PRIMARY KEY ("feedback_id", "question");

ALTER TABLE ONLY "public"."feedback"
    ADD CONSTRAINT "feedback_pkey" PRIMARY KEY ("id");

CREATE INDEX "idx_review_prof_email_created_at" ON "professor"."review" USING "btree" ("professor_email", "created_at" DESC) WHERE ("deleted_at" IS NULL);

CREATE INDEX "idx_review_rating_session_review" ON "professor"."review_rating" USING "btree" ("session_id", "review_id");

CREATE INDEX "professor_university_index" ON "professor"."professor" USING "btree" ("university");

CREATE INDEX "reply_like_user_id_index" ON "professor"."reply_like" USING "btree" ("user_id");

CREATE INDEX "review_rating_user_id_review_id_session_id_index" ON "professor"."review_rating" USING "btree" ("user_id", "review_id", "session_id");

CREATE INDEX "review_reply_review_id_created_at_index" ON "professor"."review_reply" USING "btree" ("review_id", "created_at");

CREATE INDEX "review_reply_user_id_index" ON "professor"."review_reply" USING "btree" ("user_id");

CREATE INDEX "review_session_id_index" ON "professor"."review" USING "btree" ("session_id");

CREATE INDEX "review_user_id_index" ON "professor"."review" USING "btree" ("user_id");

CREATE OR REPLACE FUNCTION "public"."trg_decrement_rating"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    IF OLD.value THEN
        UPDATE professor.review 
        SET like_count = GREATEST(like_count - 1, 0) 
        WHERE id = OLD.review_id;
    ELSIF NOT OLD.value THEN
        UPDATE professor.review 
        SET dislike_count = GREATEST(dislike_count - 1, 0) 
        WHERE id = OLD.review_id;
    END IF;
    RETURN OLD;
END;
$$;

CREATE OR REPLACE FUNCTION "public"."trg_increment_rating"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    IF NEW.value THEN
        UPDATE professor.review 
        SET like_count = like_count + 1 
        WHERE id = NEW.review_id;
    ELSIF NOT NEW.value THEN
        UPDATE professor.review 
        SET dislike_count = dislike_count + 1 
        WHERE id = NEW.review_id;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION "public"."trg_reply_like_decrement"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    UPDATE professor.review_reply
    SET like_count = GREATEST(like_count - 1, 0)
    WHERE id = OLD.reply_id;
    RETURN OLD;
END;
$$;

CREATE OR REPLACE FUNCTION "public"."trg_reply_like_increment"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    UPDATE professor.review_reply
    SET like_count = like_count + 1
    WHERE id = NEW.reply_id;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION "public"."update_review_reply_count"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$begin
    -- Increment when inserting a non-deleted, visible reply
    if (TG_OP = 'INSERT') then
        update professor.review
        set reply_count = reply_count + 1
        where id = NEW.review_id;
    end if;

    -- Decrement when marking deleted
    if (TG_OP = 'UPDATE') then
        if (OLD.deleted_at is null and OLD.visible = true)  -- was counted
           and not (NEW.deleted_at is null and NEW.visible = true)  -- not counted anymore
        then
            update professor.review
            set reply_count = reply_count - 1
            where id = NEW.review_id;
        elsif not (OLD.deleted_at is null and OLD.visible = true)  -- was not counted
              and (NEW.deleted_at is null and NEW.visible = true)  -- now counted
        then
            update professor.review
            set reply_count = reply_count + 1
            where id = NEW.review_id;
        end if;
    end if;

    return NEW;
end;$$;

CREATE OR REPLACE TRIGGER "review_reply_count_trigger" AFTER INSERT OR UPDATE ON "professor"."review_reply" FOR EACH ROW EXECUTE FUNCTION "public"."update_review_reply_count"();

CREATE OR REPLACE TRIGGER "trg_ratings_after_delete" AFTER DELETE ON "professor"."review_rating" FOR EACH ROW EXECUTE FUNCTION "public"."trg_decrement_rating"();

CREATE OR REPLACE TRIGGER "trg_ratings_after_insert" AFTER INSERT ON "professor"."review_rating" FOR EACH ROW EXECUTE FUNCTION "public"."trg_increment_rating"();

CREATE OR REPLACE TRIGGER "trg_reply_like_after_delete" AFTER DELETE ON "professor"."reply_like" FOR EACH ROW EXECUTE FUNCTION "public"."trg_reply_like_decrement"();

CREATE OR REPLACE TRIGGER "trg_reply_like_after_insert" AFTER INSERT ON "professor"."reply_like" FOR EACH ROW EXECUTE FUNCTION "public"."trg_reply_like_increment"();

ALTER TABLE ONLY "course"."file"
    ADD CONSTRAINT "file_course_tag_fkey" FOREIGN KEY ("course_tag") REFERENCES "course"."course"("tag");

ALTER TABLE ONLY "professor"."reply_like"
    ADD CONSTRAINT "reply_like_reply_id_fkey" FOREIGN KEY ("reply_id") REFERENCES "professor"."review_reply"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "professor"."reply_name"
    ADD CONSTRAINT "reply_name_review_id_fkey" FOREIGN KEY ("review_id") REFERENCES "professor"."review"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "professor"."review"
    ADD CONSTRAINT "review_professor_email_fkey" FOREIGN KEY ("professor_email") REFERENCES "professor"."professor"("email") ON UPDATE CASCADE;

ALTER TABLE ONLY "professor"."review_rating"
    ADD CONSTRAINT "review_rating_review_id_fkey" FOREIGN KEY ("review_id") REFERENCES "professor"."review"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "professor"."review_reply"
    ADD CONSTRAINT "review_reply_review_id_fkey" FOREIGN KEY ("review_id") REFERENCES "professor"."review"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "professor"."review_reply"
    ADD CONSTRAINT "review_reply_review_reply_id_fk" FOREIGN KEY ("mention_id") REFERENCES "professor"."review_reply"("id");

ALTER TABLE ONLY "professor"."review_report"
    ADD CONSTRAINT "review_report_review_id_fkey" FOREIGN KEY ("review_id") REFERENCES "professor"."review"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "professor"."review_translation"
    ADD CONSTRAINT "review_translation_review_id_fkey" FOREIGN KEY ("review_id") REFERENCES "professor"."review"("id") ON DELETE CASCADE;
