import '@/styles/globals.scss';
import {Montserrat} from 'next/font/google';
import Header from "@/components/Global/Header";
import Footer from "@/components/Global/Footer";

const montserrat = Montserrat({subsets: ['latin'], weight: ["100", "200", "300", "400", "500", "600", "700", "800"]});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={montserrat.className}>
      <body>
      <div className={"body"}>
        <Header/>

        <main>
          <div className={"main"}>
            {children}
          </div>
        </main>

        <Footer/>

        <div className={"right"}/>

      </div>
      </body>
    </html>
  )
}
