name: 'Check Vite Frontend PR'

on:
  pull_request:
    paths:
      - 'web-client/**'

jobs:
  build-and-test:
    runs-on: 'ubuntu-latest'

    defaults:
      run:
        working-directory: web-client

    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v3'

      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v3'
        with:
          node-version: '20'

      - name: 'Install dependencies'
        run: npm install

      - name: 'Build Vite app (Dry Run)'
        run: npm run build
