name: 'Build and Deploy Vite Frontend'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'web-client/**'
  pull_request:
    paths:
      - 'web-client/**'

jobs:
  build-and-deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      id-token: 'write'

    defaults:
      run:
        working-directory: web-client

    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v3'

      - name: 'Set short SHA'
        run: echo "VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v3'
        with:
          node-version: '20'

      - name: 'Install dependencies'
        run: npm install

      - name: 'Build Vite app'
        run: npm run build
        env:
          VITE_APP_VERSION: ${{ env.VERSION }}

      - name: 'Configure AWS credentials'
        uses: 'aws-actions/configure-aws-credentials@v4.3.1'
        with:
          role-to-assume: arn:aws:iam::734946078607:role/github-action
          aws-region: me-central-1

      - name: Upload versioned build
        run: |
          aws s3 sync dist s3://static.spaceread.net/${{ env.VERSION }} \
          --exclude "index.html"

      - name: Upload HTML (latest)
        run: |
          aws s3 cp dist/index.html s3://spaceread.net/www/index.html \
          --cache-control "private, no-cache, s-maxage=0, max-age=0, must-revalidate, no-store" \
          --expires "Tue, 31 Mar 1981 09:00:00 GMT" \
          --content-type "text/html; charset=utf-8" 

      - name: Upload HTML (versioned)
        run: |
          aws s3 cp s3://spaceread.net/www/index.html s3://spaceread.net/index-${VERSION}.html \
          --metadata-directive COPY
